version: v0

runs:
  - name: python example
    tasks:
      - name: test
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: python:3.8-buster
        steps:
          - clone:
          - run: python -m pip install --upgrade pip
          - run: pip install -r requirements.txt
          - run: pip install flake8
          - run:
              name: Lint stage 1
              command: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          - run:
              name: Lint stage 2
              command: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          - run: pip install pytest
          - run:
              name: Test with pytest
              command: pytest
