version: v0

runs:
  - name: java with maven example
    tasks:
      - name: build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: maven:3-jdk-8
        steps:
          - clone:
          - run:
            name: Build with maven
            command: mvn -B package --file pom.xml


