version: v0

runs:
  - name: External services example
    tasks:
      - name: Build with external services
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: busybox
              entrypoint: cat
            - image: nginx:1.16
            - image: mysql:5.7
              environment:
                MYSQL_ROOT_PASSWORD: xxx
        steps:
          - run:
              name: test nginx open
              command: nc -z localhost 80
          - run:
              name: test mysql open
              command: sleep 30 && nc -z localhost 3306
